DROP TABLE payment CASCADE;

DROP TABLE bonusshopped CASCADE;

DROP TABLE bonus CASCADE;

DROP TABLE subcategory CASCADE;

DROP TABLE category CASCADE;

DROP TABLE productlist CASCADE;

DROP TABLE productprice CASCADE;

DROP TABLE product CASCADE;

DROP TABLE shop CASCADE;

DROP TABLE shoppinglistchecked CASCADE;

DROP TABLE shoppinglistsaved CASCADE;

DROP TABLE account CASCADE;